name: Create release

on: push
#  push:
#    # Sequence of patterns matched against refs/tags
#    tags:
#      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: dart-lang/setup-dart@v1
        name: Setup Dart
      - run: dart pub get
        name: Get pub
      - run: dart test
        name: Test


generate:
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

    - outputs:
        gitTag: ${{ steps.previoustag.outputs.tag }}

  build:
    needs: [test, generate]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ needs.generate.outputs.gitTag }}
          release_name: Release ${{ needs.generate.outputs.gitTag }}
          body: cat Release.txt
          draft: false
          prerelease: false
    permissions:
      contents: write